org.gradle.jvmargs=-Xmx1536M
android.useAndroidX=true
android.enableJetifier=true
android.enableD8=true
android.enableDexingArtifactTransform=false
# org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr\\jdk-11.0.30.7-hotspot
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.19.10-hotspot